
// import ConfigureAmplify from '../components/ConfigureAmplify';
// import './globals.css';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//     return (
//     <html lang="en">
//       <body>
//         <ConfigureAmplify />
//         {children}
//       </body>
//     </html>
//   );
// }

// Remove the old ConfigureAmplify component
// import ConfigureAmplify from '@/components/ConfigureAmplify';
import AmplifyProvider from '../components/AmplifyProvider'; // Import the new provider
import { Amplify } from "aws-amplify";

import './globals.css';

export const metadata = {
  title: 'MindTracker',
  description: 'Your wellness journey starts here',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Wrap your children with the provider */}
        <AmplifyProvider>
          {children}
        </AmplifyProvider>
      </body>
    </html>
  );
}